language: d
d:
  - dmd
  - ldc
#  - gdc #seems uncapable to handle dip1008; also gdmd doesn't currently recognize -dip*

sudo: required
dist: trusty
env:
  - VERSION=1.0.18
before_install:
  - curl https://download.libsodium.org/libsodium/releases/libsodium-$VERSION.tar.gz | tar -C ~ -xzf -
  - pushd ~/libsodium-$VERSION
  - ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu && make && sudo make install
  - sudo ldconfig
  - popd

install:
  - wget -O doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.3.2/doveralls_linux_travis"
  - chmod +x doveralls

script:
  - dub test  :deimos  --compiler=${DC}
#  - dub test  :wrapper --compiler=${DC} --config=travis_minimal
  - dub build :wrapper --compiler=${DC} --config=travis --build=release
  - dub test  :wrapper --compiler=${DC} --config=travis --build=unittest-cov
  - scripts/run-doveralls.sh
# - ./doveralls
